//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lndr.Simple.CLR.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lndr.Simple.CLR.Helpers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;3tR+wUpHkv/dsrg2MHCVo3xlAJlF/K12VoWD3iSEyjWNwvu+tYnkG6gKoVVssVv+oLlPpdDqtTE9B36eXgf9X+INUaXW5IR9hJL9s/vjbOj5KZlIOHFrQDubIjo5djj1Z3nmRdQIkGwuyF6C7Sz+Svipu4Ermc5Rdfj02YEOcPk=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;/0jLDdULItLk3eYaO3fEia00riKNynJuvPxbcgeZahvHR102nbR6lveLVhKYmtKkm0W2AAf7Bn7qGd4Uw4/6Rw==&lt;/P&gt;&lt;Q&gt;33RpL4IlhnCJgranFAHLnwKApRSiLqOOVqbxT9o0AnI8ZWhBtF1S3W9aNbSaXbhh1VrvYeaXMA/UpfRaWUyavw==&lt;/Q&gt;&lt;DP&gt;n5rVSOqfscAE0y8fy3pP6Hvf6dc0qxPsZD+qtJpHsm13pAiFMwg5dNWDyeaKfpGf1Gw7I73ZlfAXUODmPnZv1Q==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CryptoPrivateKey {
            get {
                return ResourceManager.GetString("CryptoPrivateKey", resourceCulture);
            }
        }
    }
}
